server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8101
  servlet:
    context-path: /


spring:
  profiles:
    include: common
  application:
    name: bff-driver
  cloud:
    nacos:
  #    config:
  #      group: DEFAULT_GROUP
  #      file-extension: yaml
  #      server-addr: 192.168.241.131:8848
  #      prefix: ${spring.application.name}
  #      namespace: hxds
      discovery:
  #      namespace: hxds
  #      username: nacos
  #      password: nacos
        server-addr: 192.168.241.131:8848
  #      heart-beat-interval: 1000
  #      heart-beat-timeout: 1000
  #      group: DEFAULT_GROUP

  redis:
    database: 3
    host: 192.168.241.131
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

sa-token:
  token-name: token
  # 单位是s
  timeout: 864000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: true
  token-style: uuid
  is-read-cookie: false


springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 300000