server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8102
  servlet:
    context-path: /


spring:
  profiles:
    #引用application-common.yml文件
    include: common
  application:
    name: bff-customer
  cloud:
    inetutils:
      #子系统注册到Nacos上的IP地址
      preferred-networks: 127.0.0.1
    nacos:
      #配置子系统在web管理页面上的注册信息
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        prefix: ${spring.application.name}
        namespace: hxds
      discovery:
        #配置子系统在Nacos上的注册信息
        namespace: hxds
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 1000
        group: DEFAULT_GROUP

  redis:
    database: 4
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

sa-token:
  token-name: token
  # 单位是s
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  is-read-cookie: false


springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 300000