spring:
  profiles: common

tencent:
  secretId: secretId
  secretKey: secretKey
  region-public: ??
  bucket-public: ??
  region-private: ??
  bucket-private: ??


wx:
  app-id: AppID
  app-secret: ??
  mch-id: ???ID
  key: ?????
  cert-path: ????

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456
