spring:
  profiles: common

tencent:
  cloud:
    appId: 1323891151
    secretId: 
    secretKey:
    region-public: ap-guangzhou
    bucket-public: hxds-public-1323891151
    region-private: ap-guangzhou
    bucket-private: hxds-private-1323891151

wx:
  app-id: 你的微信小程序APPID
  app-secret: 你的微信小程序密钥
  mch-id: 商户号（课程QQ群共享文件中获取）
  key: 商户密钥（课程QQ群共享文件中获取）
  cert-path: 商户数字证书文件路径（课程QQ群共享文件中获取）

minio:
  endpoint: http://192.168.241.130:9000
  access-key: root
  secret-key: abc123456
